from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("src/BackGround-v5.png"))
        self.background.setScaledContents(True)
        self.cur_time = QtWidgets.QLabel(self.centralwidget)
        self.cur_time.setGeometry(QtCore.QRect(400, 180, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cur_time.setFont(font)
        self.cur_time.setObjectName("cur_time")
        self.song_name = QtWidgets.QLabel(self.centralwidget)
        self.song_name.setGeometry(QtCore.QRect(400, 110, 380, 32))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.song_name.setFont(font)
        self.song_name.setObjectName("song_name")
        self.total_time = QtWidgets.QLabel(self.centralwidget)
        self.total_time.setGeometry(QtCore.QRect(710, 180, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.total_time.setFont(font)
        self.total_time.setObjectName("total_time")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(453, 185, 250, 10))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setStyleSheet("QProgressBar{"
                                        "border-radius: 4px;"
                                        "background-color: qlineargradient"
                                        "(spread:pad, x1:0.463054, y1:0.0965909, x2:0.487685, y2:0.813,"
                                        "stop:0 rgba(56, 56, 56, 150), stop:1 rgba(40, 40, 40, 150));}"
                                        "QProgressBar::chunk{"
                                        "border-radius: 4px;"
                                        "background-color: qlineargradient"
                                        "(spread:pad, x1:0.463054, y1:0.0965909, x2:0.487685, y2:0.813, "
                                        "stop:0 rgba(40, 113, 250, 150), stop:1 rgba(103, 23, 205, 150));}")
        self.progressBar.setFormat('')
        self.progressBar.setObjectName("progressBar")
        self.volume_slider = QtWidgets.QSlider(self.centralwidget)
        self.volume_slider.setGeometry(QtCore.QRect(260, 553, 160, 25))
        self.volume_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volume_slider.setValue(88)
        self.volume_slider.setObjectName("volume_slider")
        self.volume_button = QtWidgets.QPushButton(self.centralwidget)
        self.volume_button.setGeometry(QtCore.QRect(200, 540, 42, 42))
        self.volume_button.setAutoFillBackground(False)
        self.volume_button.setText("")
        iconV = QtGui.QIcon()
        iconV.addPixmap(QtGui.QPixmap("src/sound.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.volume_button.setIcon(iconV)
        self.volume_button.setIconSize(QtCore.QSize(42, 42))
        self.volume_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button.setGeometry(QtCore.QRect(20, 540, 42, 42))
        self.pause_button.setAutoFillBackground(False)
        self.pause_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/pause.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pause_button.setIcon(icon)
        self.pause_button.setIconSize(QtCore.QSize(32, 32))
        self.pause_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.pause_button.setObjectName("pause")
        self.hidenButton = QtWidgets.QPushButton(self.centralwidget)
        self.hidenButton.setGeometry(QtCore.QRect(20, 540, 42, 42))
        self.hidenButton.setAutoFillBackground(False)
        self.hidenButton.setText("")
        iconk = QtGui.QIcon()
        iconk.addPixmap(QtGui.QPixmap("src/pause.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.hidenButton.setIcon(iconk)
        self.hidenButton.setIconSize(QtCore.QSize(32, 32))
        self.hidenButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.hidenButton.hide()
        self.prev_button = QtWidgets.QPushButton(self.centralwidget)
        self.prev_button.setGeometry(QtCore.QRect(80, 540, 42, 42))
        self.prev_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.prev_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/prev.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.prev_button.setIcon(icon1)
        self.prev_button.setIconSize(QtCore.QSize(32, 32))
        self.prev_button.setCheckable(False)
        self.prev_button.setObjectName("prev")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(130, 540, 42, 42))
        self.next_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.next_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("src/next.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.Off)
        self.next_button.setIcon(icon2)
        self.next_button.setIconSize(QtCore.QSize(32, 32))
        self.next_button.setObjectName("next")
        self.settings_button = QtWidgets.QPushButton(self.centralwidget)
        self.settings_button.setGeometry(QtCore.QRect(718, 535, 45, 45))
        self.settings_button.setAutoFillBackground(False)
        self.settings_button.setText("")
        self.icon3 = QtGui.QIcon()
        self.icon3.addPixmap(QtGui.QPixmap("src/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings_button.setIcon(self.icon3)
        self.settings_button.setIconSize(QtCore.QSize(42, 42))
        self.settings_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.add_song_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_song_button.setGeometry(QtCore.QRect(720, 535, 42, 42))
        self.add_song_button.setAutoFillBackground(False)
        self.add_song_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("src/folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_song_button.setIcon(icon4)
        self.add_song_button.setIconSize(QtCore.QSize(32, 32))
        self.add_song_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.add_song_button.hide()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", ""))
        self.cur_time.setText(_translate("MainWindow", "00:00"))
        self.song_name.setText(_translate("MainWindow", "Add music to folder"))
        self.total_time.setText(_translate("MainWindow", "03:00"))